export const MATERIALS: Material[] = [
  {
    name: "Бронза",
    icon: "ph:medal-fill",
    color: "black",
    id: 2,
  },
  {
    name: "Латунь",
    icon: "mingcute:bowl-line",
    color: "black",
    id: 3,
  },
  {
    name: "Алюминий",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 4,
  },
  {
    name: "Свинец",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 5,
  },
  {
    name: "Олово",
    icon: "lets-icons:ring-fill",
    color: "black",
    id: 6,
  },
  {
    name: "Никель",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 7,
  },
  {
    name: "Нихром",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 8,
  },
  {
    name: "Мельхиор",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 9,
  },
  {
    name: "Нержавейка",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 10,
  },
  {
    name: "Лом Стали",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 11,
  },
  {
    name: "Черный Металл",
    icon: "ant-design:gold-filled",
    color: "black",
    id: 12,
  },
  {
    name: "Резина",
    icon: "cil:scrubber",
    color: "black",
    id: 13,
  },
  {
    name: "Макулатура/ Бумага",
    icon: "wpf:cut-paper",
    color: "black",
    id: 14,
  },
  {
    name: "Аккумуляторы",
    icon: "game-icons:batteries",
    color: "black",
    id: 15,
  },
  {
    name: "Батарейки",
    icon: "clarity:battery-line",
    color: "black",
    id: 16,
  },
  {
    name: "Пластмасса",
    icon: "guidance:plastic",
    color: "black",
    id: 17,
  },
  {
    name: "Медь",
    icon: "mingcute:copper-coin-line",
    color: "orange",
    id: 1,
  },
];
